env:
  global:
    secure: "ZfIyB3ySTgfOHxA/KK86qQdyfQSUuf6uSS73bSNA40gTS9UXPMudbH2+OCIIkxe7gzJLI89T4grTkdKLsvBrk7Blz1Dg5zL0bVaDRKsCOW16VZqfi0szENH0xa3HrtnmlIBc/PP85CNQRtIhTnw/M/J0wCswfO3vBiSYekQ+s8EcwKXPTIL94Cp9f3TYgkn5vN0503cCl+wKuG0r0swSpQRJHMybh5Ghi4fRUwiS28PTtL1VTkBe7YTdCyk2I+pD6Ay2Pilyov+FxUXyv8GRIje3hM+1cqFMV7mtfoNkHTOG4s+4Tipzuu4NcHYgBcX1aXK1nzAiUUe4mcu2ESMldzdj5qZMl2rdwd8doRtf738WYm7e6FtP3UdUvVk90dhXR1uzvY4q0zK0nIc0wdclVznWJ8dhqRwRRM1udpPuUJ9msFEErQlkJ4kawZgkRzctW6kxHV6Us4i4Wf7Mc0c9mKUG/6dE6CMOjbM914Ab5mci9nInaMFbo4SzWImB0Vpuvp/KJFEbWSxqwfme7ZhM2IzlYKy/6P2kRLirQot1L19lYrjn4KAQdjBnSMA3Kqkpo9/or0cjnGePhNhWSArLoLBunXFZo38hKBySc8rIXuLS1WNmeJUvmo2Gu7g73hKIPErjN58dkUbirGLUe6AOPxsYXrnf6W357bjhxoHjWwI="

language: python
sudo: false
notifications:
  email: false

install:
  - pip install mkdocs
  - pip install git+https://github.com/r0wb0t/markdown-urlize@master

script:
  - git clone -b gh-pages https://${GH_TOKEN}@github.com/ModDocs/eureka/ ../gh-pages > /dev/null 2>&1
  - mkdocs build --clean --site-dir ../gh-pages
  - cd ../gh-pages
  - git add -A
  - git config --global user.email "contact@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git commit -am "CI Update"
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] && git push > /dev/null 2>&1 || true'
