site_name: Eureka
site_favicon: img/favicon.ico
repo_url: https://github.com/ModDocs/eureka
strict: true

markdown_extensions:
  - smarty
  - urlize
  - tables
  - fenced_code

pages:
  - Home: index.md
